{% set name = "fairseq" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/fairseq/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4328a7cb5fe6aea874817a863eb7f1ace91d621bc504345e6d022ce64e065da0

build:
  number: 0
  entry_points:
    - fairseq-eval-lm = fairseq_cli.eval_lm:cli_main
    - fairseq-generate = fairseq_cli.generate:cli_main
    - fairseq-interactive = fairseq_cli.interactive:cli_main
    - fairseq-preprocess = fairseq_cli.preprocess:cli_main
    - fairseq-score = fairseq_cli.score:cli_main
    - fairseq-train = fairseq_cli.train:cli_main
    - fairseq-validate = fairseq_cli.validate:cli_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools

  run:
    - python
    - cffi
    - {{ pin_compatible('numpy') }}
    - regex
    - sacrebleu
    - cython
    - pytorch
    - tqdm
    - dataclasses
    - hydra-core

test:
  imports:
    - fairseq
    - fairseq.benchmark
  commands:
    - fairseq-eval-lm --help
    - fairseq-generate --help
    - fairseq-interactive --help
    - fairseq-preprocess --help
    - fairseq-score --help
    - fairseq-train --help
    - fairseq-validate --help

about:
  home: https://github.com/pytorch/fairseq
  summary: Facebook AI Research Sequence-to-Sequence Toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sdvillal
  original-recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
